package me.kyllian.netflixstatistix.exceptions;

public enum InvalidFieldType {

    FIRSTNAME, LASTNAME, PASSWORDUNSAFE, DIFFERENTPASSWORD, EMAIL, EMAILEXISTS, STREET, NUMBER, POSTALCODE, RESIDENCE, BIRTHDATE, DATABASETIMEOUT, UNKNOWNACCOUNT, INCORRECTPASSWORD;
}
